import { X } from "lucide-react";
import { createPortal } from "react-dom";

const GeminiModal = ({
   isOpen,
   setIsOpen,
   productSummary,
   product_title,
   loading,
}) => {
   const render = () =>
      isOpen && (
         <div
            className="w-screen h-screen bg-[rgba(255,255,255,0.4)] flex items-center justify-center fixed top-0 left-0 z-10"
            onClick={() => setIsOpen(false)}
         >
            <div
               className="w-1/2 relative border border-slate-200 p-10 flex items-center justify-center gap-2 flex-col rounded-lg shadow-md bg-white overflow-hidden"
               onClick={(e) => e.stopPropagation()}
            >
               <h1 className="text-4xl font-bold text-center">
                  Product Summary generated by GeminiAI 1.5 Flash
               </h1>
               <button
                  onClick={() => setIsOpen(false)}
                  className="absolute top-2 right-2 cursor-pointer"
               >
                  <X className="w-5" />
               </button>
               <span className="text-xs text-blue-500 text-center underline">
                  {product_title}
               </span>
               {loading ? <span>loading..</span> : <div>{productSummary}</div>}
            </div>
         </div>
      );

   return createPortal(render(), document.getElementById("gemini-modal"));
};

export default GeminiModal;
