export const p = [
   {
      asin: "B0CWXNS552",
      product_title: "Apple AirTag",
      product_price: "$24.99",
      product_original_price: "$29.00",
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 2027,
      product_url: "https://www.amazon.com/dp/B0CWXNS552",
      product_photo:
         "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 11,
      product_minimum_offer_price: "$23.33",
      is_best_seller: false,
      is_amazon_choice: true,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "10K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0D5FZGY8W",
      product_title:
         "URO Vaginal Probiotics for Women pH Balance with Prebiotics &amp; Lactobacillus Probiotic Blend - Women&#x27;s Vaginal Health Supplement - Promote Healthy Vaginal Odor &amp; Vaginal Flora, 60 Count (Pack of 1)",
      product_price: "$28.79",
      unit_price: "$0.48",
      unit_count: 60,
      product_original_price: "$31.99",
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 376,
      product_url: "https://www.amazon.com/dp/B0D5FZGY8W",
      product_photo:
         "https://m.media-amazon.com/images/I/61tYAHJi3LL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$28.79",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: true,
      sales_volume: "100K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "1665955430",
      product_title: "Reckless (The Powerless Trilogy)",
      product_price: "$14.97",
      product_original_price: "$21.99",
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 2160,
      product_url: "https://www.amazon.com/dp/1665955430",
      product_photo:
         "https://m.media-amazon.com/images/I/81q6ecxcZUL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 37,
      product_minimum_offer_price: "$14.96",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0CS12LZLS",
      product_title: "NESCAFÉ Gold Espresso Blonde, Instant Coffee, 3.5 oz",
      product_price: "$6.68",
      unit_price: "$1.91",
      unit_count: 3,
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 278,
      product_url: "https://www.amazon.com/dp/B0CS12LZLS",
      product_photo:
         "https://m.media-amazon.com/images/I/71tPLfAANDL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$6.68",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "10K+ bought in past month",
      delivery:
         "FREE delivery Jul 15 - 17 on $35 of items shipped by AmazonOr fastest delivery Jul 14 - 16",
      has_variations: false,
   },
   {
      asin: "B0CSBZVR6F",
      product_title:
         "2 Pack Continuous Spray Bottles - Ultra Fine Mist Sprayer | Water Spray Bottle For Hair Mister Spray Bottle | Hair Spray Bottles For Hairstyling, Cleaning, Salons - 2pk 6.8 OZ / 200 ML",
      product_price: "$8.48",
      product_original_price: "$8.99",
      currency: "USD",
      product_star_rating: "4.3",
      product_num_ratings: 2110,
      product_url: "https://www.amazon.com/dp/B0CSBZVR6F",
      product_photo:
         "https://m.media-amazon.com/images/I/71Grc+h-AtL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 5,
      product_minimum_offer_price: "$2.45",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: true,
      sales_volume: "20K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "1668032147",
      product_title: "Protocols: An Operating Manual for the Human Body",
      product_price: "$21.39",
      product_original_price: "$35.00",
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/1668032147",
      product_photo:
         "https://m.media-amazon.com/images/I/61tDi3+vgzL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$21.39",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery:
         "FREE delivery Mon, Apr 28, 2025 on $35 of items shipped by AmazonOr fastest delivery Tue, Apr 22, 2025 This title will be released on April 22, 2025.",
      has_variations: false,
   },
   {
      asin: "0593657470",
      product_title: "On Call: A Doctor&#x27;s Journey in Public Service",
      product_price: "$22.59",
      product_original_price: "$36.00",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 780,
      product_url: "https://www.amazon.com/dp/0593657470",
      product_photo:
         "https://m.media-amazon.com/images/I/813MUJ9ftIL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$22.59",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0CV4FQPY1",
      product_title:
         "Bounty Select-A-Size Paper Towels, White, 8 Triple Rolls = 24 Regular Rolls",
      product_price: "$22.18",
      unit_price: "$2.05",
      unit_count: 11,
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.8",
      product_num_ratings: 35935,
      product_url: "https://www.amazon.com/dp/B0CV4FQPY1",
      product_photo:
         "https://m.media-amazon.com/images/I/81jYzN4cAdL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 15,
      product_minimum_offer_price: "$21.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "40K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0C9N2L56X",
      product_title:
         "The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness",
      product_price: "$0.00",
      product_original_price: "$20.25",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 1764,
      product_url: "https://www.amazon.com/dp/B0C9N2L56X",
      product_photo:
         "https://m.media-amazon.com/images/I/81N4drWaxuL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "1464221138",
      product_title: "The Housemaid Is Watching",
      product_price: "$12.71",
      product_original_price: "$17.99",
      currency: "USD",
      product_star_rating: "4.2",
      product_num_ratings: 56803,
      product_url: "https://www.amazon.com/dp/1464221138",
      product_photo:
         "https://m.media-amazon.com/images/I/91OSM58Y-pL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 52,
      product_minimum_offer_price: "$10.50",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0CSYG2CP3",
      product_title:
         "Car Carplay Cable for iPhone 15 15 Pro Max 15 Plus Cable, USB A to USB C for Carplay USB C Cord, iPad usb C Cable 10th Gen iPad Pro iPad Air 5th 4th Mini 6th Gen Car Charger Cable Cord Replacement 3FT",
      product_price: "$8.19",
      product_original_price: "$8.99",
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 596,
      product_url: "https://www.amazon.com/dp/B0CSYG2CP3",
      product_photo:
         "https://m.media-amazon.com/images/I/61fpyOCUDML._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$8.19",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "10K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B07RFSSYBH",
      product_title:
         "Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones",
      product_price: "$0.00",
      product_original_price: "$18.00",
      currency: "USD",
      product_star_rating: "4.8",
      product_num_ratings: 129547,
      product_url: "https://www.amazon.com/dp/B07RFSSYBH",
      product_photo:
         "https://m.media-amazon.com/images/I/71F4+7rk2eL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0CQDFPMQW",
      product_title:
         "LMNT Zero-Sugar Electrolytes - Variety Pack Bundle - Drink Mix | No Dodgy Ingredients | Keto &amp; Paleo Friendly | 36 Sticks",
      product_price: "$59.99",
      unit_price: "$7.90",
      unit_count: 8,
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 17598,
      product_url: "https://www.amazon.com/dp/B0CQDFPMQW",
      product_photo:
         "https://m.media-amazon.com/images/I/81qGH-6amTL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$59.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "20K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10",
      has_variations: false,
   },
   {
      asin: "B0CP93N5S2",
      product_title: "All the Colors of the Dark",
      product_price: "$13.99",
      product_original_price: "$30.00",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 856,
      product_url: "https://www.amazon.com/dp/B0CP93N5S2",
      product_photo:
         "https://m.media-amazon.com/images/I/81RBcyIyl2L._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$13.99",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Print List Price: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0D3PBB78P",
      product_title: "EA SPORTS College Football 25 - PlayStation 5",
      product_price: "$69.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0D3PBB78P",
      product_photo:
         "https://m.media-amazon.com/images/I/81aE0GBL2mL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$69.99",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jul 19, 2024",
      delivery: "FREE deliveryThis item will be released on July 19, 2024.",
      has_variations: false,
   },
   {
      asin: "B0D49X2P79",
      product_title: "Twister [4K UHD]",
      product_price: "$24.96",
      product_original_price: "$33.99",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 2119,
      product_url: "https://www.amazon.com/dp/B0D49X2P79",
      product_photo:
         "https://m.media-amazon.com/images/I/71HH+CAgaJL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$24.96",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "2K+ bought in past month",
      delivery:
         "FREE delivery Wed, Jul 17 on $35 of items shipped by AmazonOr fastest delivery Tue, Jul 16 This title will be released on July 9, 2024.",
      has_variations: false,
   },
   {
      asin: "B0CLKQF5HR",
      product_title: "Swan Song",
      product_price: "$14.99",
      product_original_price: "$30.00",
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 7102,
      product_url: "https://www.amazon.com/dp/B0CLKQF5HR",
      product_photo:
         "https://m.media-amazon.com/images/I/71dSn3QCY6L._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$14.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Print List Price: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0D2PKQGQV",
      product_title:
         "Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack",
      product_price: "$21.98",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.4",
      product_num_ratings: 24675,
      product_url: "https://www.amazon.com/dp/B0D2PKQGQV",
      product_photo:
         "https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$21.98",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "500+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: true,
   },
   {
      asin: "B0D1P158BH",
      product_title: "UEFA EURO 2024 Official",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "3.4",
      product_num_ratings: 56,
      product_url: "https://www.amazon.com/dp/B0D1P158BH",
      product_photo:
         "https://m.media-amazon.com/images/I/71Eq+TtkQRL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jun 14, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0D74SZ9NS",
      product_title: "Metal Gear Solid Selections Original Soundtrack",
      product_price: "$54.98",
      product_original_price: null,
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0D74SZ9NS",
      product_photo:
         "https://m.media-amazon.com/images/I/81TEJmhug0L._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$54.98",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: null,
      delivery:
         "FREE delivery Tue, Oct 22 Or fastest delivery Fri, Oct 18 This title will be released on October 18, 2024.",
      has_variations: false,
   },
   {
      asin: "B0D7MC3XH1",
      product_title: "YOYO School: YOYO Doll School life Dress up",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "5",
      product_num_ratings: 3,
      product_url: "https://www.amazon.com/dp/B0D7MC3XH1",
      product_photo:
         "https://m.media-amazon.com/images/I/81m++AruMtL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jun 20, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0CZ7NKH1T",
      product_title: "Triviascapes: relaxing trivia &amp; IQ quiz",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.2",
      product_num_ratings: 23,
      product_url: "https://www.amazon.com/dp/B0CZ7NKH1T",
      product_photo:
         "https://m.media-amazon.com/images/I/71DhfojGRZL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Apr 10, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0CGVSQHNG",
      product_title: "Deeper Than the Dead (Vera Boyett Book 1)",
      product_price: "$4.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.3",
      product_num_ratings: 171,
      product_url: "https://www.amazon.com/dp/B0CGVSQHNG",
      product_photo:
         "https://m.media-amazon.com/images/I/817KwFYx4gL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$4.99",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "This title will be released on August 1, 2024.",
      has_variations: false,
   },
   {
      asin: "B0D81GQ96G",
      product_title: "Smarter IP-TV : Player Pro",
      product_price: "$12.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "3.8",
      product_num_ratings: 4,
      product_url: "https://www.amazon.com/dp/B0D81GQ96G",
      product_photo:
         "https://m.media-amazon.com/images/I/61jFyIhWbTL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$12.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jun 26, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0D8K3Z4FT",
      product_title:
         "Ys Memoire The Oath of Felghana Nintendo Switch - D1 Refined Edition",
      product_price: "$59.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0D8K3Z4FT",
      product_photo:
         "https://m.media-amazon.com/images/I/71LhvZ3JUpL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$59.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Mar 31, 2025",
      delivery: "FREE deliveryThis item will be released on March 31, 2025.",
      has_variations: false,
   },
   {
      asin: "1538742578",
      product_title: "The Housemaid",
      product_price: "$6.96",
      product_original_price: "$12.99",
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 319190,
      product_url: "https://www.amazon.com/dp/1538742578",
      product_photo:
         "https://m.media-amazon.com/images/I/81AHTyq2wVL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 119,
      product_minimum_offer_price: "$3.06",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0D73NMM7N",
      product_title: "Fluvsies Merge Party",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "5",
      product_num_ratings: 2,
      product_url: "https://www.amazon.com/dp/B0D73NMM7N",
      product_photo:
         "https://m.media-amazon.com/images/I/81k3RzdCdxL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jun 27, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0D7W5JY1Y",
      product_title:
         "Paramount Presents: Bringing Out the Dead [4K UHD + Blu-Ray + Digital Copy]",
      product_price: "$39.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 1119,
      product_url: "https://www.amazon.com/dp/B0D7W5JY1Y",
      product_photo:
         "https://m.media-amazon.com/images/I/61pWQhd0-hL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$39.99",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "1K+ bought in past month",
      delivery:
         "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
      has_variations: false,
   },
   {
      asin: "B0CKNM2RS7",
      product_title: "Eruption",
      product_price: "$0.00",
      product_original_price: "$21.83",
      currency: "USD",
      product_star_rating: "4.3",
      product_num_ratings: 9813,
      product_url: "https://www.amazon.com/dp/B0CKNM2RS7",
      product_photo:
         "https://m.media-amazon.com/images/I/91jZ4396SPL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0D8J9HYGD",
      product_title:
         "Kingdom Of The Planet Of The Apes - UHD/BD Combo + Digital + Steelbook [4K UHD]",
      product_price: "$65.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0D8J9HYGD",
      product_photo:
         "https://m.media-amazon.com/images/I/81O+BMeRFsL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$65.99",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery:
         "$10.21 delivery Tue, Aug 27 This title will be released on August 27, 2024.",
      has_variations: false,
   },
   {
      asin: "B0D1XD1ZV3",
      product_title:
         "Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio",
      product_price: "$249.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 1009,
      product_url: "https://www.amazon.com/dp/B0D1XD1ZV3",
      product_photo:
         "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 5,
      product_minimum_offer_price: "$206.80",
      is_best_seller: false,
      is_amazon_choice: true,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "10K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10",
      has_variations: false,
   },
   {
      asin: "B0D7TY6C1H",
      product_title:
         "Late Night With the Devil - Limited Edition Steelbook [Blu-Ray]",
      product_price: "$35.68",
      product_original_price: "$49.99",
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0D7TY6C1H",
      product_photo: null,
      product_num_offers: 1,
      product_minimum_offer_price: "$35.68",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "500+ bought in past month",
      delivery:
         "FREE delivery Mon, Sep 16 Or fastest delivery Tue, Sep 10 This title will be released on September 10, 2024.",
      has_variations: false,
   },
   {
      asin: "B0CQYH6LQ9",
      product_title:
         "8 Pack Refill Cartridge Kit Compatible with ZEVO Plug-in Light M364 and Max, Replacement 100% Fit (8 Refill Cartridges)",
      product_price: "$15.29",
      unit_price: "$1.91",
      unit_count: 8,
      product_original_price: "$17.99",
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 1420,
      product_url: "https://www.amazon.com/dp/B0CQYH6LQ9",
      product_photo:
         "https://m.media-amazon.com/images/I/71iEIPz+JSL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$15.29",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "40K+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0D7KR99VL",
      product_title: "Get unlimited Free Robux 2024",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "1",
      product_num_ratings: 2,
      product_url: "https://www.amazon.com/dp/B0D7KR99VL",
      product_photo:
         "https://m.media-amazon.com/images/I/71H3ahAWJHL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Jun 20, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0CPWYVX6H",
      product_title: "Energizer 2450 Lithium Coin Battery, 2 Pack",
      product_price: "$5.44",
      unit_price: "$2.72",
      unit_count: 2,
      product_original_price: "$8.98",
      currency: "USD",
      product_star_rating: "4.8",
      product_num_ratings: 1570,
      product_url: "https://www.amazon.com/dp/B0CPWYVX6H",
      product_photo:
         "https://m.media-amazon.com/images/I/71LSsuHdVBL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 11,
      product_minimum_offer_price: "$5.42",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "1K+ bought in past month",
      delivery: "FREE delivery Jul 11 - 15",
      has_variations: false,
   },
   {
      asin: "B0CX9CM41G",
      product_title: "Block Mini Craft Village",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: null,
      product_num_ratings: 0,
      product_url: "https://www.amazon.com/dp/B0CX9CM41G",
      product_photo:
         "https://m.media-amazon.com/images/I/81H6mknKhaL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "May 31, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B00OZP5VRS",
      product_title: "A Court of Thorns and Roses",
      product_price: "$8.21",
      product_original_price: "$15.20",
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 215583,
      product_url: "https://www.amazon.com/dp/B00OZP5VRS",
      product_photo:
         "https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$8.21",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Digital List Price: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0D4FBLRTC",
      product_title: "People Sandbox Playgrounds",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "1.8",
      product_num_ratings: 3,
      product_url: "https://www.amazon.com/dp/B0D4FBLRTC",
      product_photo:
         "https://m.media-amazon.com/images/I/51vhEIwynYL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "May 17, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0D8JTTX3D",
      product_title: "The Chronicles Of Riddick 4K UHD",
      product_price: "$49.95",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 7745,
      product_url: "https://www.amazon.com/dp/B0D8JTTX3D",
      product_photo:
         "https://m.media-amazon.com/images/I/8115yTKlBCL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$49.95",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "500+ bought in past month",
      delivery:
         "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
      has_variations: false,
   },
   {
      asin: "B0C4QD5VPB",
      product_title: "The Women: A Novel",
      product_price: "$0.00",
      product_original_price: "$24.74",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 124461,
      product_url: "https://www.amazon.com/dp/B0C4QD5VPB",
      product_photo:
         "https://m.media-amazon.com/images/I/91mP3553EzL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0CCPPQ38D",
      product_title: "Funny Story",
      product_price: "$0.00",
      product_original_price: "$20.25",
      currency: "USD",
      product_star_rating: "4.5",
      product_num_ratings: 42953,
      product_url: "https://www.amazon.com/dp/B0CCPPQ38D",
      product_photo:
         "https://m.media-amazon.com/images/I/71MmozgfmVL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Other formats: ",
      delivery: "Available instantly",
      has_variations: false,
   },
   {
      asin: "B0D37QVQW4",
      product_title: "MLB: Baseball Super League",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.1",
      product_num_ratings: 51,
      product_url: "https://www.amazon.com/dp/B0D37QVQW4",
      product_photo:
         "https://m.media-amazon.com/images/I/81LYuFcyLlL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "May 24, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "B0D3VHPLW1",
      product_title: "Furiosa: A Mad Max Saga (4K Ultra HD + Digital)",
      product_price: "$29.96",
      product_original_price: "$49.98",
      currency: "USD",
      product_star_rating: "4.4",
      product_num_ratings: 130,
      product_url: "https://www.amazon.com/dp/B0D3VHPLW1",
      product_photo:
         "https://m.media-amazon.com/images/I/81cqVE2vwvL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$29.96",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "3K+ bought in past month",
      delivery:
         "FREE delivery Mon, Aug 19 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 13 This title will be released on August 13, 2024.",
      has_variations: false,
   },
   {
      asin: "0140280197",
      product_title: "The 48 Laws of Power",
      product_price: "$14.55",
      product_original_price: "$26.00",
      currency: "USD",
      product_star_rating: "4.7",
      product_num_ratings: 77785,
      product_url: "https://www.amazon.com/dp/0140280197",
      product_photo:
         "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 170,
      product_minimum_offer_price: "$7.91",
      is_best_seller: true,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0CQCDMY2V",
      product_title: "The Beekeeper",
      product_price: "$3.99",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 24293,
      product_url: "https://www.amazon.com/dp/B0CQCDMY2V",
      product_photo:
         "https://m.media-amazon.com/images/I/91yFa4jlW0L._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$3.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "2024",
      delivery: null,
      has_variations: false,
   },
   {
      asin: "B0CX379HYG",
      product_title:
         "Dickies Men&#x27;s Dri-tech Moisture Control No Show Socks (6/12 Pairs) (M-XXL)",
      product_price: "$15.99",
      unit_price: "$2.67",
      unit_count: 6,
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.6",
      product_num_ratings: 17423,
      product_url: "https://www.amazon.com/dp/B0CX379HYG",
      product_photo:
         "https://m.media-amazon.com/images/I/91VLjxlAbtL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 1,
      product_minimum_offer_price: "$15.99",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "600+ bought in past month",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
   {
      asin: "B0CW188Z2N",
      product_title: "Football League 2024",
      product_price: "$0.00",
      product_original_price: null,
      currency: "USD",
      product_star_rating: "4.1",
      product_num_ratings: 47,
      product_url: "https://www.amazon.com/dp/B0CW188Z2N",
      product_photo:
         "https://m.media-amazon.com/images/I/81qVL2BFWhL._AC_UL960_FMwebp_QL65_.png",
      product_num_offers: 1,
      product_minimum_offer_price: "$0.00",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: false,
      climate_pledge_friendly: false,
      sales_volume: "Feb 26, 2024",
      delivery: "Available instantly on compatible devices",
      has_variations: false,
   },
   {
      asin: "0349132615",
      product_title: "The Housemaid&#x27;s Secret",
      product_price: "$7.68",
      product_original_price: "$12.99",
      currency: "USD",
      product_star_rating: "4.4",
      product_num_ratings: 168531,
      product_url: "https://www.amazon.com/dp/0349132615",
      product_photo:
         "https://m.media-amazon.com/images/I/81LZXcfKqJL._AC_UL960_FMwebp_QL65_.jpg",
      product_num_offers: 58,
      product_minimum_offer_price: "$5.67",
      is_best_seller: false,
      is_amazon_choice: false,
      is_prime: true,
      climate_pledge_friendly: false,
      sales_volume: "List: ",
      delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
      has_variations: false,
   },
];

const googleResponse = {
   user: {
      uid: "cOXBqWYtdyNskdYed4SxNTFMeTF3",
      email: "prempravinsapkale@gmail.com",
      emailVerified: true,
      displayName: "Prem Sapkale",
      isAnonymous: false,
      photoURL:
         "https://lh3.googleusercontent.com/a/ACg8ocKme-ujJM-gkiK8klOtlqNtiIRNd8vw8JwgdJHfSjy8mKtmYA=s96-c",
      providerData: [
         {
            providerId: "google.com",
            uid: "101538497255911241300",
            displayName: "Prem Sapkale",
            email: "prempravinsapkale@gmail.com",
            phoneNumber: null,
            photoURL:
               "https://lh3.googleusercontent.com/a/ACg8ocKme-ujJM-gkiK8klOtlqNtiIRNd8vw8JwgdJHfSjy8mKtmYA=s96-c",
         },
      ],
      stsTokenManager: {
         refreshToken:
            "AMf-vByh1OIDgdJcAtW4rFhCtAauCo13eibk6lE4WUeDY6k7d-O85JSpXD5ouDOQszXK0HCYSr1SVw5DN5CjlSnMdiX6i9iIvWwALtxBQcZBDSOrXSuu58eqOpdx1NZlT60smQBu0tY202vgoHzgdWOjnMCDIQ4kv_yDH2lePuWISVJnXCDVWs8RpgK-XmHC0OifJOS0MwrzFAF-Noy9irjnzPo0Q2RxuXV0ah0L8CT4MATRYUJwtQd9jz5iAJUeH4IoBOU_KQdH7YoJtG_damNTdbvEu1d-F0pkAl_WhUPBhsWVeuV6o2-5HjEr1Sl9PxmgXte3P4T6hbLDxVMErV-BzcQE0AsS7R72u41zbqSY4otfBflTuqXAbJJ7yrxXCQ20RmIIm6fJTghWFjbdSVn26mActMcRpyljkUdr_PdTt5-BOkOe7hQ",
         accessToken:
            "eyJhbGciOiJSUzI1NiIsImtpZCI6IjgxYjUyMjFlN2E1ZGUwZTVhZjQ5N2UzNzVhNzRiMDZkODJiYTc4OGIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUHJlbSBTYXBrYWxlIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0ttZS11akpNLWdraUs4a2xPdGxxTnRpSVJOZDh2dzhKd2dkSkhmU2p5OG1LdG1ZQT1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9nZnMtbW9kdWxlNSIsImF1ZCI6Imdmcy1tb2R1bGU1IiwiYXV0aF90aW1lIjoxNzM3OTcxMTIxLCJ1c2VyX2lkIjoiY09YQnFXWXRkeU5za2RZZWQ0U3hOVEZNZVRGMyIsInN1YiI6ImNPWEJxV1l0ZHlOc2tkWWVkNFN4TlRGTWVURjMiLCJpYXQiOjE3Mzc5NzExMjEsImV4cCI6MTczNzk3NDcyMSwiZW1haWwiOiJwcmVtcHJhdmluc2Fwa2FsZUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjEwMTUzODQ5NzI1NTkxMTI0MTMwMCJdLCJlbWFpbCI6WyJwcmVtcHJhdmluc2Fwa2FsZUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.Dy94Mcj7-4H-vQSz4CnIXDu5f0d881MrlEy8CQgF2fWEFQqSVv_5Jy1jdyeUnh5j-jICHAtUdOOaoLYJAVVsvz8c-XXDqc6vkja4cFYKlaY8TIJNpMPf0znU0atCz4w43Pqwlyz_u8PkCvCXGBWnmiOY1GWCDQMaz_gh3Z5lepKmj5GdBPxbAzQS0Il_IdNfDbxTT9cIsubh-wQKI2J0CyhG_lUhYwf05qpV21pX6KvhCl6AR9sXb7x3R4_G1lKdemFjmCwh541guuiiMhHoPqawX2Y-ibrrnkDmkAnoDVy8-OjxeGWjTlzryhUaMEtjLz4cg82t7FL79nDeyFWXJg",
         expirationTime: 1737974721728,
      },
      createdAt: "1736484162971",
      lastLoginAt: "1737971081719",
      apiKey: "AIzaSyA2_IMrL6cQykJy_UIBu09oqUvQmtQDGBA",
      appName: "[DEFAULT]",
   },
   providerId: "google.com",
   _tokenResponse: {
      federatedId: "https://accounts.google.com/101538497255911241300",
      providerId: "google.com",
      email: "prempravinsapkale@gmail.com",
      emailVerified: true,
      firstName: "Prem",
      fullName: "Prem Sapkale",
      lastName: "Sapkale",
      photoUrl:
         "https://lh3.googleusercontent.com/a/ACg8ocKme-ujJM-gkiK8klOtlqNtiIRNd8vw8JwgdJHfSjy8mKtmYA=s96-c",
      localId: "cOXBqWYtdyNskdYed4SxNTFMeTF3",
      displayName: "Prem Sapkale",
      idToken:
         "eyJhbGciOiJSUzI1NiIsImtpZCI6IjgxYjUyMjFlN2E1ZGUwZTVhZjQ5N2UzNzVhNzRiMDZkODJiYTc4OGIiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiUHJlbSBTYXBrYWxlIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0ttZS11akpNLWdraUs4a2xPdGxxTnRpSVJOZDh2dzhKd2dkSkhmU2p5OG1LdG1ZQT1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9nZnMtbW9kdWxlNSIsImF1ZCI6Imdmcy1tb2R1bGU1IiwiYXV0aF90aW1lIjoxNzM3OTcxMTIxLCJ1c2VyX2lkIjoiY09YQnFXWXRkeU5za2RZZWQ0U3hOVEZNZVRGMyIsInN1YiI6ImNPWEJxV1l0ZHlOc2tkWWVkNFN4TlRGTWVURjMiLCJpYXQiOjE3Mzc5NzExMjEsImV4cCI6MTczNzk3NDcyMSwiZW1haWwiOiJwcmVtcHJhdmluc2Fwa2FsZUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJnb29nbGUuY29tIjpbIjEwMTUzODQ5NzI1NTkxMTI0MTMwMCJdLCJlbWFpbCI6WyJwcmVtcHJhdmluc2Fwa2FsZUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.Dy94Mcj7-4H-vQSz4CnIXDu5f0d881MrlEy8CQgF2fWEFQqSVv_5Jy1jdyeUnh5j-jICHAtUdOOaoLYJAVVsvz8c-XXDqc6vkja4cFYKlaY8TIJNpMPf0znU0atCz4w43Pqwlyz_u8PkCvCXGBWnmiOY1GWCDQMaz_gh3Z5lepKmj5GdBPxbAzQS0Il_IdNfDbxTT9cIsubh-wQKI2J0CyhG_lUhYwf05qpV21pX6KvhCl6AR9sXb7x3R4_G1lKdemFjmCwh541guuiiMhHoPqawX2Y-ibrrnkDmkAnoDVy8-OjxeGWjTlzryhUaMEtjLz4cg82t7FL79nDeyFWXJg",
      context: "",
      oauthAccessToken:
         "ya29.a0AXeO80RutFAQSEbtcQMZ-h1Pa8lDXITViymPLSOvpf2HmAQmNcNTFgE2bmbLPmMKhWenqLC6iO3cCnJr4TsXxUlzLfncR2gMb765LYi-GiOSpLVJ5GrH0xPEjT2LapJp2ugFb8p-z0D0AjuVq7m0pb54JzgT9FIjJgMaCgYKAdoSARASFQHGX2MihIXIGFySExxLx7NCSJzEwA0170",
      oauthExpireIn: 3597,
      refreshToken:
         "AMf-vByh1OIDgdJcAtW4rFhCtAauCo13eibk6lE4WUeDY6k7d-O85JSpXD5ouDOQszXK0HCYSr1SVw5DN5CjlSnMdiX6i9iIvWwALtxBQcZBDSOrXSuu58eqOpdx1NZlT60smQBu0tY202vgoHzgdWOjnMCDIQ4kv_yDH2lePuWISVJnXCDVWs8RpgK-XmHC0OifJOS0MwrzFAF-Noy9irjnzPo0Q2RxuXV0ah0L8CT4MATRYUJwtQd9jz5iAJUeH4IoBOU_KQdH7YoJtG_damNTdbvEu1d-F0pkAl_WhUPBhsWVeuV6o2-5HjEr1Sl9PxmgXte3P4T6hbLDxVMErV-BzcQE0AsS7R72u41zbqSY4otfBflTuqXAbJJ7yrxXCQ20RmIIm6fJTghWFjbdSVn26mActMcRpyljkUdr_PdTt5-BOkOe7hQ",
      expiresIn: "3600",
      oauthIdToken:
         "eyJhbGciOiJSUzI1NiIsImtpZCI6IjYzMzdiZTYzNjRmMzgyNDAwOGQwZTkwMDNmNTBiYjZiNDNkNWE5YzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiMzI5MDEwNTk2MzE1LTFlOGtlN2hmNWQ2MWNrbzE3amw4b2s5ZWd1cXR2ODZjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMzI5MDEwNTk2MzE1LTFlOGtlN2hmNWQ2MWNrbzE3amw4b2s5ZWd1cXR2ODZjLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAxNTM4NDk3MjU1OTExMjQxMzAwIiwiZW1haWwiOiJwcmVtcHJhdmluc2Fwa2FsZUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6ImRJMmRMQjZPcDQyd0hnOW5sdnBUTHciLCJpYXQiOjE3Mzc5NzExMjEsImV4cCI6MTczNzk3NDcyMX0.JNv-sHk6gEhOLkA6FZb6CZBVgtiV7mrbkJLwfqM2FciBamhRZ0vB9YJGvUyq0ctbkP-i9A3v3bQBNdwwKv4AWbi2GxPLpYTG_sTwL2je1pzWiFb1e_IsMV1Sukakkr96zAQ1jrushgkSL7WdMuW5_tUHevk_174WmU_6u05As-BmVaJyhdoB28alyL27D6LWQZJk5exAlf_7K61ne7lf7LXrH5xUdASvUfcvV15yqM2dvuROZFm77nXcaWXkZbZdR8AugPb5sCNEFVaD6zF1_g6KVsrpXYdoThgjKVi4ZaOaNCMsM2DFpPOlWYgD1WAaYa-c98hezl7TzUfAPBV8Wg",
      rawUserInfo:
         '{"name":"Prem Sapkale","granted_scopes":"https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/userinfo.email","id":"101538497255911241300","verified_email":true,"given_name":"Prem","family_name":"Sapkale","email":"prempravinsapkale@gmail.com","picture":"https://lh3.googleusercontent.com/a/ACg8ocKme-ujJM-gkiK8klOtlqNtiIRNd8vw8JwgdJHfSjy8mKtmYA=s96-c"}',
      kind: "identitytoolkit#VerifyAssertionResponse",
   },
   operationType: "signIn",
};
